### PR TITLE
Add authorization spec files

### PR DESCRIPTION
**Pull request by tsolakoua**

### CODE REVIEW

**Review by jabrena — APPROVED** [review]
I have verified at different levels:

- [x]  Spec validation with: https://github.com/OpenAPITools/openapi-style-validator
- [x] Code generation with: https://github.com/OpenAPITools/openapi-generator
- [x] Usage of Code generated with success

I am happy with the PR

Juan Antonio

**Comment by jabrena** [comment]
Next week, I will release a repository to validate any new Spec easily for the whole team.

**Comment by gimperial** [comment]
Stupid question @tsolakoua and @jabrena, in our postman regression we also have a GET endpoint for the authorization, shouldn't we also add this one in our specification?

**Review by gimperial — APPROVED** [review]

**Comment by jabrena** [comment]
Yes, this week I will send a PR with the missing endpoint.

**Pull request merged**
